version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "80:8000"
    # command: gunicorn --workers=4 --bind 0.0.0.0:8000 IETE_CTF.wsgi:application
    command: python manage.py runserver 0.0.0.0:8000
